version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - SECRET_KEY=your_secret_key
    depends_on:
      - db
    command: >
      sh -c "flask db upgrade &&
             flask init-db &&
             flask run --host=0.0.0.0"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
